# Update packages and configure our C2 infrastructure
- hosts: localhost
  vars_prompt:
    - name: cobalt_strike_license
      prompt: What cobalt strike license should I use?
      private: no
# Get EC2 variables
  tasks:
    - name: Get info from Teamserver
      amazon.aws.ec2_instance_info:
        region: "{{ aws_region }}"
        profile: "{{ aws_profile }}"
        filters:
          "tag:user": "{{ engagement_lead }}"
          "tag:customer": "{{ customer }}"
          "tag:type": "c2_teamserver"
          instance-state-name: [ "pending", "running" ]
      register: teamserver

    - name: Get info from Redirector
      amazon.aws.ec2_instance_info:
        region: "{{ aws_region }}"
        profile: "{{ aws_profile }}"
        filters:
          "tag:user": "{{ engagement_lead }}"
          "tag:customer": "{{ customer }}"
          "tag:type": "c2_front"
          instance-state-name: [ "pending", "running" ]
      register: redirector

# Set hostvars  
    - set_fact:
        team_private_ip: "{{ teamserver.instances[0]['private_ip_address'] }}"
        team_public_ip: "{{ teamserver.instances[0]['public_ip_address'] }}"
        front_private_ip: "{{ redirector.instances[0]['private_ip_address'] }}"
        front_public_ip: "{{ redirector.instances[0]['public_ip_address'] }}"
        front_dns_name: "{{ redirector.instances[0]['public_dns_name'] }}"
        glob_customer: "{{ customer }}"
        cobalt: "{{ cobalt_strike_license }}"

# Update packages on Teamserver and Redirector
- hosts:
  - "tag_customer_{{ hostvars['localhost']['glob_customer'] }}"
  become: True
  tasks:
  - name: Update all packages to their latest version
    apt:
      name: "*"
      state: latest
      update_cache: yes
      cache_valid_time: 3600
  - name: Upgrade the OS (apt-get dist-upgrade)
    apt:
      upgrade: dist
  - name: Update repositories cache and install additional packages
    apt:
      pkg:
      - rsync
      - ca-certificates
      - openjdk-17-jdk
      - screen
      - tmux
      - net-tools
      - socat
      state: present
      update_cache: yes
      cache_valid_time: 6

# Copy Cobalt Strike license & update Cobalt Strike (Cobalt Strike binaries are already packaged on AMI)
- hosts:
  - "tag_customer_{{ hostvars['localhost']['glob_customer'] }}:&tag_type_c2_teamserver"
  become: True
  tasks:
  - name: Copy resolv.conf to server
    copy:
      src: "./files/resolv.conf"
      dest: "/etc/resolv.conf"
  - service_facts:
  - name: stop and disable systemd-resolved
    service:
      name: systemd-resolved
      state: stopped
      enabled: false
  - name: Copy Cobalt Strike License to Team Server
    template:
      src: "./files/.cobaltstrike.license"
      dest: .cobaltstrike.license
  - name: Create Tools directory
    file:
      path: /home/ubuntu/Tools
      state: directory
      owner: ubuntu
      group: ubuntu
  - name: Unzip Cobalt Strike to Team server
    unarchive:
      src: "./files/cobaltstrike-dist-linux.tgz"
      dest: /home/ubuntu/Tools/
  - name: Update Cobalt Strike
    ansible.builtin.expect: 
      timeout: 180
      chdir: /home/ubuntu/Tools/cobaltstrike
      command: ./update
      responses:
        (?i)Please enter your license key: "{{ hostvars['localhost']['cobalt'] }}"

# Add MOTD to Teamserver
- hosts:
  - "tag_customer_{{ hostvars['localhost']['glob_customer'] }}:&tag_type_c2_teamserver"
  become: True
  tasks:
  - name: Copy MOTD template to /etc/motd
    template:
      src: "./files/team_motd"
      dest: /etc/motd
      owner: root
      group: root
      mode: '644'
  - name: Update Private IP
    ansible.builtin.lineinfile:
      path: /etc/motd
      regexp: '^Private IP:'
      line: "Private IP: {{ hostvars['localhost']['team_private_ip'] }}"
      insertbefore: "BOF"
      state: present
  - name: Update Public IP
    ansible.builtin.lineinfile:
      path: /etc/motd
      regexp: '^Public IP:'
      line: "Public IP: {{ hostvars['localhost']['team_public_ip'] }}"
      insertbefore: "BOF"
      state: present
  - name: Update Public IP
    ansible.builtin.lineinfile:
      path: /etc/motd
      regexp: '^Redirector Public IP:'
      line: "Redirector Public IP: {{ hostvars['localhost']['front_public_ip'] }}"
      insertbefore: "BOF"
      state: present
  - name: Update MOTD Hint
    ansible.builtin.lineinfile:
      path: /etc/motd
      regexp: "^To start:"
      line: "To start the Cobalt Strike Teamserver, run: 'teamserver {{ hostvars['localhost']['front_public_ip'] }} <password> [/path/to/c2.profile] [YYYY-MM-DD]'"
      insertbefore: "BOF"
      state: present
      
# Add MOTD to Redirector
- hosts:
  - "tag_customer_{{ hostvars['localhost']['glob_customer'] }}:&tag_type_c2_front"
  become: True
  tasks:
  - name: Copy MOTD template to /etc/motd
    template:
      src: "./files/front_motd"
      dest: /etc/motd
      owner: root
      group: root
      mode: '644'
  - name: Update Private IP
    ansible.builtin.lineinfile:
      path: /etc/motd
      regexp: '^Private IP:'
      line: "Private IP: {{ hostvars['localhost']['front_private_ip'] }}"
      insertbefore: "BOF"
      state: present
  - name: Update Private IP
    ansible.builtin.lineinfile:
      path: /etc/motd
      regexp: '^Public IP:'
      line: "Public IP: {{ hostvars['localhost']['front_public_ip'] }}"
      insertbefore: "BOF"
      state: present

# Add alias to quickly launch Cobalt Strike Teamserver
- hosts:
  - "tag_customer_{{ hostvars['localhost']['glob_customer'] }}:&tag_type_c2_teamserver"
  become: True
  tasks:
  - name: Add teamserver alias for ubuntu user
    lineinfile:
      path=/home/ubuntu/.bashrc
      line="alias teamserver='cd /home/ubuntu/Tools/cobaltstrike/server/ && sudo ./teamserver'"
      owner=ubuntu
      regexp="^alias teamserver='cd /home/ubuntu/Tools/cobaltstrike/server/ && sudo ./teamserver'"
      state=present
      insertafter=EOF
      create=True

# Configure DNS/HTTP/HTTPS forwarding on Redirector
- hosts:
  - "tag_customer_{{ hostvars['localhost']['glob_customer'] }}:&tag_type_c2_front"
  become: True
  tasks:
# Set up DNS forwarding
    - name: Install dnsmasq
      apt:
        pkg:
        - dnsmasq
        state: present
        update_cache: yes
        cache_valid_time: 6
    - name: Copy dnsmasq config to server
      template:
        src: "./files/dnsmasq.conf"
        dest: "/etc/dnsmasq.conf"
    - name: Copy resolv.conf to server
      copy:
        src: "./files/resolv.conf"
        dest: "/etc/resolv.conf"
    - service_facts:
    - name: stop and disable systemd-resolved
      service:
        name: systemd-resolved
        state: stopped
        enabled: false
    - name: start and enable dnsmasq
      service:
        name: dnsmasq
        state: started
        enabled: true
    - ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
# Set up HTTP/HTTPS forwarding
    - name: Copy socat.sh to redirector
      template:
        src: "./files/socat.sh"
        dest: "/home/ubuntu/socat.sh"
        owner: ubuntu
        group: ubuntu
        mode: '755'        
    - name: Edit socat.sh to forward HTTPS
      ansible.builtin.lineinfile:
        path: /home/ubuntu/socat.sh
        regexp: '^sudo socat TCP4-LISTEN:443,fork TCP4:front_private_ip:443 >/dev/null 2>&1 &'
        line: "sudo socat TCP4-LISTEN:443,fork TCP4:{{ hostvars['localhost']['team_private_ip'] }}:443 >/dev/null 2>&1 &"
        insertbefore: "BOF"
        state: present
    - name: Edit socat.sh to forward HTTP
      ansible.builtin.lineinfile:
        path: /home/ubuntu/socat.sh
        regexp: '^sudo socat TCP4-LISTEN:80,fork TCP4:front_private_ip:80 >/dev/null 2>&1 &'
        line: "sudo socat TCP4-LISTEN:80,fork TCP4:{{ hostvars['localhost']['team_private_ip'] }}:80 >/dev/null 2>&1 &"
        insertbefore: "BOF"
        state: present
    - name: Add socat.sh to ~/.profile
      ansible.builtin.lineinfile:
        path: /home/ubuntu/.profile
        regexp: '^/home/ubuntu/socat.sh'
        line: "/home/ubuntu/socat.sh"
        insertafter: "EOF"
        state: present
    - name: Create a cron job to make sure socat is running every 5 minutes
      ansible.builtin.cron:
        name: "socat"
        minute: "*/5"
        job: "/home/ubuntu/socat.sh"
        user: ubuntu
        state: present
        